name: Agendamento Noturno 00:00hr

on:
  schedule:    
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-at-night:
    runs-on: ubuntu-latest
    steps:
      - name: Tarefa noturna
        run: echo "Rodando a tarefa da noite... (Agendado para 00:00hr)"
