name: Agendamento Sábado

on:
  schedule:    
    - cron: '0 10 * * 6'
  workflow_dispatch:

jobs:
  run-on-saturday:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo
    steps:
      - name: Tarefa de Sábado
        run: echo "Hoje é sábado, hora de rodar o job!"
