name: Usuario Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Mostra o Usuário
        run: echo "Push feito por ${{ github.actor }}"
